import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/Theme";
import Navbar from "@/components/navigation/navbar";
import LeftSideBar from "@/components/navigation/LeftSideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <Navbar />
          <div className="flex">
            {/* Left sidebar navigation */}
            <LeftSideBar />

            {/* Main content area with padding and responsive adjustments */}
            <section className="flex min-h-screen flex-1 flex-col px-6 pb-6 sm:px-14">
              {/* Centered container with a maximum width for content */}
              <div className="mx-auto w-full max-w-5xl">
                {children} {/* Render the page-specific content here */}
              </div>
            </section>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
